/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {

  public static void main(String[] args) {
    
    Scanner scan = new Scanner(System.in);
    System.out.println("번호?\n");
    int no = scan.nextInt();
    
    System.out.println("수업명?\n");
    String Cn = scan.next();
    System.out.println("수업내용?\n");
    String Cd = scan.next();
    System.out.println("시작일?\n");
    String Sd = scan.next();
    System.out.println("종료일?\n");
    String Ed = scan.next();
    System.out.println("총수업시간?\n");
    int Ot = scan.nextInt();
    System.out.println("일수업시간?\n");
    int Dt = scan.nextInt();
    
    
    System.out.printf("%d, %s ,%s ~ %s,%s\n",no,Cn,Sd,Ed,Dt);

    
  }
}

//System.out.println("daily?");