/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {

  public static void main(String[] args) {
    
    Scanner scan = new Scanner(System.in);

    final int SIZE = 10000;
    
    class Lesson {
    //    int[] count = new int[size];
    int number;
    String title;
    String description;
    Date startdate;
    Date enddate;
    int totalhours;
    int dayhours;     
    }


    int count = 0;
    String response;
    
    Lesson[] lessons = new Lesson[SIZE];
    int i;
    /*
    for(i = 0; i < SIZE; i ++) {
     Lessons[i] = new Lesson();
    }
    */
    
    
    for(i = 0 ; i < SIZE; i ++) {      
      
      count++;
      //사용자 입력한 게시물 데이터를 저장할 메모리를 Board 설계도에 따라 만든다
      //Lesson ls = Lessons[i];
      
      Lesson ls = new Lesson(); //인스턴트 배열 매 루프마다 생성 - 멤버 설계도에 따라 메모리를 만듦
      
      System.out.print("번호?");

      ls.number = scan.nextInt();

      scan.nextLine();

      System.out.print("수업명?\n");    

      ls.title = scan.nextLine();

      System.out.print("수업내용?\n");

      ls.description = scan.nextLine();

      System.out.print("시작일?\n");    

      ls.startdate = Date.valueOf(scan.next());    

      System.out.print("종료일?\n");

      ls.enddate = Date.valueOf(scan.next());

      System.out.print("총수업시간?\n");

      ls.totalhours = scan.nextInt();

      System.out.print("일수업시간?\n");

      ls.dayhours = scan.nextInt();

      scan.nextLine();//남아있는 줄바꿈 값 제거
      
      //수업 정보를 담고 있는 인스턴스의 주소를 나중에 사용할 수 있도록 레퍼런스 배열에 보관
      lessons[i] = ls;
      
      System.out.println();
      
      System.out.println("계속 입력 (Y/n)");
      
      response = scan.nextLine();
      
      
      if(!response.equalsIgnoreCase("y")) {
        break;
      }
      
     }
      System.out.println();
      
      for(i = 0; i < count; i ++) 
      {
        Lesson ls = lessons[i];
        
        System.out.printf("%d, %s ,%s ~ %s,%d\n",ls.number,ls.title,ls.startdate,
            ls.enddate,ls.totalhours);
      }
      System.out.println();
      scan.close();
    }
    // count[0] = 0;
  }


//System.out.println("daily?");