/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.util.Scanner;

public class App {

  public static void main(String[] args) {

    Scanner keyboard = new Scanner(System.in); // keyboard에서 사용자가 입력한 값을 읽어 문자열 정수 부동소수점등으로 리턴하는 역할
    System.out.println("number?\n");
    String no = keyboard.nextLine();
    
    System.out.println("number\n" + no);
    
    System.out.println("classN?\n");
    String ao = keyboard.nextLine();
    
    System.out.println("classN\n" + ao);
    
    System.out.println("exzplain?\n");
    String bo = keyboard.nextLine();
    
    System.out.println("explain\n" + bo);
    
    System.out.println("explainsda\n");
    
    String co = keyboard.nextLine();
    
    System.out.println("explainasda\n" + co);
    
//    System.out.println("explain\n");
   
    System.out.println("startdate\n");    
    String eo = keyboard.nextLine();
    
//    System.out.println("startdate\t" + eo);
    
    
    System.out.println("enddate\t");
    
    String fo = keyboard.nextLine();
//    System.out.println("enddate\t" + fo);
    

    

    System.out.printf("overall: %s ~ %s \n" , eo,fo);
    
    System.out.println("daily?");
    
    String po = keyboard.nextLine();
    System.out.println("daily" + po);
    
  
     keyboard.close();

  }
}
